#!/usr/bin/ruby

Directory="/home/aaf/scripts/control"
#require "#{Directory}/xml_parser.rb"
require "#{Directory}/cal.rb"
require "#{Directory}/gui.rb"
require 'date'

CALENDAR_FILE = "#{Directory}/Calendar.csv"

class MainApp
	def initialize(configfile) 

		# And launch that first screen
		Gtk.init
		app = Win.new(configfile)
		Gtk.main
	end	
end

app = MainApp.new(CALENDAR_FILE)

